function FlightData_1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  FLIGHTDATA_1 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  FLIGHTDATA_1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  FLIGHTDATA_1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  FlightData_1 = importfile("C:\Users\agarcian\OneDrive - MathWorks\Documents\CSE Info\Accounts\Dallas College\low-code-data-analysis-main-2026\nasa-aircraft-low-code\Demos\FlightData.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Sep-2026 10:31:28

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Time", "FuelQuantity", "OilPressure", "OilTemperature", "LatitudePosition", "LongitudePosition", "Altitude", "ExhaustTemperature", "FuelFlow", "FanSpeed", "TrueAirSpeed", "WindDirection", "WindSpeed", "WeightOnWheels"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
FlightData_1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    FlightData_1 = [FlightData_1; tb]; %#ok<AGROW>
end

end